// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArAFhFce91-7cjtH2cRzcGZAesoDVwar4',
    appId: '1:699175464839:web:07650220ab9fbaa33fad22',
    messagingSenderId: '699175464839',
    projectId: 'senacanuncios',
    authDomain: 'senacanuncios.firebaseapp.com',
    storageBucket: 'senacanuncios.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQsUdPaYAKFz8tcvQF-C_Y4QThhvVbWBU',
    appId: '1:699175464839:android:e6f729a150186cc73fad22',
    messagingSenderId: '699175464839',
    projectId: 'senacanuncios',
    storageBucket: 'senacanuncios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaFmqoECn2S2v6aWu8UhLO33-tcTntt4c',
    appId: '1:699175464839:ios:649b00a4e3dfdd153fad22',
    messagingSenderId: '699175464839',
    projectId: 'senacanuncios',
    storageBucket: 'senacanuncios.appspot.com',
    iosClientId: '699175464839-4h5fkql5l8tml9qgvs6vj5ufm4uo5c7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.anuncios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaFmqoECn2S2v6aWu8UhLO33-tcTntt4c',
    appId: '1:699175464839:ios:649b00a4e3dfdd153fad22',
    messagingSenderId: '699175464839',
    projectId: 'senacanuncios',
    storageBucket: 'senacanuncios.appspot.com',
    iosClientId: '699175464839-4h5fkql5l8tml9qgvs6vj5ufm4uo5c7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.anuncios',
  );
}
